organization = "TSs"
environment = "Devv"
app = "ADOo"
tier = "Webb"
rgname = "RGg1"
loc ="Canada Central"
vnet_name = "Vnett1"
vnet_address = ["11.0.0.0/16"]
subnet_name = "subnett01"
subnet_address = ["11.0.0.0/24"]
nic = "NICc"
pip = "pipp1"
NSG = "NSGg1"
vmname = "VMm1"
tagging = {
    CreatedBy = "TrustedSavvy Teamm"
    CostCenter = 123
    Org = "TSs"
}